import Head from "next/head";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";

import { Grid } from "@mui/material";
import { useRef, useState } from "react";

import TopMenu from "@/components/TopMenu";
import GameBanner from "@/components/GameBanner";
import Chat, { newMessageType } from "@/components/Chat";
import GameSheetSidePanel from "@/components/GameSheetSidePanel";
import CharacterSheetSidePanel from "@/components/CharacterSheetSidePanel";
import characters from "@/gameData/characters";

export default function Play({
  gameName = "Guardiões de Althea",
  bannerImg = require("../public/images/altheaBack.jpg"),
}) {
  const menuColors = { color: "#6750A4", hover: "#6750A4" };

  const [messages, setMessages] = useState<newMessageType[]>([]);
  const [currentCharacter, setCurrentCharacter] = useState<{
    id: number;
    name: string;
  }>(characters[0]);

  const imgRef = useRef(null);

  // useEffect(() => {
  //   console.log(currentCharacter);
  //   if (currentCharacter && currentCharacter) {
  //     setMessages((messages: any[]) => {
  //       const newMessage = {
  //         text: currentCharacter.name,
  //         color: "error",
  //         author: currentCharacter.name,
  //         timestamp: new Date(),
  //         side: "LEFT",
  //       };
  //       return [...messages, newMessage];
  //     });
  //   }
  // }, [currentCharacter]);

  // const fac = new FastAverageColor();
  // //TODO - Change text color based on background image average color
  // useEffect(() => {
  //   fac
  //     .getColorAsync(imgRef.current)
  //     .then((color) => {
  //       console.log(color);
  //       // container.style.backgroundColor = color.rgba;
  //       // container.style.color = color.isDark ? "#fff" : "#000";
  //     })
  //     .catch((e) => {
  //       console.log(e);
  //     });

  //   return () => {};
  // }, [fac, imgRef]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            height: "100svh",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <section>
            <Container>
              <TopMenu colors={menuColors} small={true}></TopMenu>
            </Container>
            <GameBanner banner={bannerImg} title={gameName}></GameBanner>
          </section>

          <Grid container sx={{ flexGrow: 1 }}>
            <Grid xs={3} item={true}>
              <CharacterSheetSidePanel
                currentCharracter={currentCharacter}
                setCurrentCharacter={setCurrentCharacter}
              ></CharacterSheetSidePanel>
            </Grid>
            <Grid
              xs={6}
              sx={{ borderInline: "1px solid #d8d8d8" }}
              padding={2}
              item={true}
            >
              <Chat
                author={currentCharacter.name}
                messages={messages}
                setMessages={setMessages}
              ></Chat>
            </Grid>
            <Grid xs={3} item={true}>
              <GameSheetSidePanel
                setMessages={setMessages}
              ></GameSheetSidePanel>
            </Grid>
          </Grid>

          <Box>
            <Typography variant="h5" component="h2">
              Footer
            </Typography>
          </Box>
        </Box>
      </main>
    </>
  );
}
