import Head from "next/head";
import Image from "next/image";
import Button from "@mui/material/Button";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import Link from "@/src/Link";
import SwipeView from "@/components/SwipeView";
import styles from "@/styles/Home.module.scss";

import pushBackgroundImg from "../public/images/pushBackground.jpg";
import push from "../public/images/push.png";
import pushLogo from "../public/images/pushLogo.png";
import seasonImg from "../public/images/season.jpeg";

import { Avatar, Grid, Paper, Stack, TextField } from "@mui/material";
import CasinoOutlinedIcon from "@mui/icons-material/CasinoOutlined";
import { SetStateAction, useEffect, useRef, useState } from "react";

import { FastAverageColor } from "fast-average-color";
import TopMenu from "@/components/TopMenu";
import GameBanner from "@/components/GameBanner";
import ScrollableDiv from "@/components/ScrollableDiv";
import Chat, { newMessageType } from "@/components/Chat";
import GameSheetView from "@/components/GameSheetView";

export default function Play({
  gameName = "Guardiões de Althea",
  bannerImg = require("../public/images/altheaBack.jpg"),
}) {
  const menuColors = { color: "#6750A4", hover: "#6750A4" };

  const [messages, setMessages] = useState<newMessageType[]>([]);

  const imgRef = useRef(null);

  // const fac = new FastAverageColor();
  // //TODO - Change text color based on background image average color
  // useEffect(() => {
  //   fac
  //     .getColorAsync(imgRef.current)
  //     .then((color) => {
  //       console.log(color);
  //       // container.style.backgroundColor = color.rgba;
  //       // container.style.color = color.isDark ? "#fff" : "#000";
  //     })
  //     .catch((e) => {
  //       console.log(e);
  //     });

  //   return () => {};
  // }, [fac, imgRef]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            height: "100svh",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <section>
            <Container>
              <TopMenu colors={menuColors} small={true}></TopMenu>
            </Container>
            <GameBanner banner={bannerImg} title={gameName}></GameBanner>
          </section>

          <Grid container sx={{ flexGrow: 1 }}>
            <Grid xs={3}>
              <Typography variant="h5" component="h2">
                Character Sheet
              </Typography>
            </Grid>
            <Grid xs={6} sx={{ borderInline: "1px solid #d8d8d8" }} padding={2}>
              <Chat
                author={"My Character Name"}
                messages={messages}
                setMessages={setMessages}
              ></Chat>
            </Grid>
            <Grid xs={3}>
              <GameSheetView setMessages={setMessages}></GameSheetView>
            </Grid>
          </Grid>

          <Box>
            <Typography variant="h5" component="h2">
              Footer
            </Typography>
          </Box>
        </Box>
      </main>
    </>
  );
}
